modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "mavapi"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies.mavapi]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mavapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"