modVersion=2.3.0
modId=mavapi
modName=More Axolotl Variants API
modDescription=Implementation of new axolotl variants. For the second time.

modrinthId=t4Ybtys2
curseforgeSlug=mavapi
curseforgeId=709964
githubProject=AkashiiKun/MoreAxolotlVariantsAPI-Common

deps.fabricLoader=0.19.3

org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
